import styles from "./../../styles/Layout.module.css";
import Head from "next/head";
export default function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>World Ranks</header>
      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>@ Dreamtusk Solutions</footer>
    </div>
  );
}
