import Head from "next/head";
import styles from "./../styles/Layout.module.css";
export default function MainLayout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Markdown Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <nav className={styles.C_navbar}>
          <p>Code With Viki</p>
        </nav>
      </header>
      <main className={styles.main}>{children}</main>
      <footer className={styles.footer}>dreamtusk</footer>
    </div>
  );
}
